### ISSUE TITLE
TypeError: _bulk_create() got an unexpected keyword argument 'ignore_conflicts'

### ISSUE THREAD

**Issue by scshivam** [martinphellwig/django-query-signals#1]
While adding groups with permission from Django Admin Panel and adding other M2M relationships too. I got this error!!

It says : TypeError: _bulk_create() got an unexpected keyword argument 'ignore_conflicts'

After some work, I found it was working with Django 2.2.12 but failed with Django 3 and above. Also, it failed due to django_query_signals since this worked after disabling django_query_signals

My Code:
```
class GroupSerializer(serializers.ModelSerializer):
    permissions = PermissionSerializerGroup(many=True, required=False)

    class Meta:
        model = Group
        fields = ('id', 'name', 'permissions')
        extra_kwargs = {
            'name': {'validators': []},
        }

    def create(self, validated_data):
        print(validated_data)
        permissions_data = validated_data.pop("permissions")
        obj, group = Group.objects.update_or_create(name=validated_data["name"])
        obj.permissions.clear()
        for permission in permissions_data:
            per = Permission.objects.get(codename=permission["codename"])
            obj.permissions.add(per)
        obj.save()
        return obj
```

Error Traceback:
```
File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1566, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1107, in save_related
    form.save_m2m()
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/forms/models.py", line 442, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/db/models/fields/related.py", line 1618, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 1008, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 946, in add
    through_defaults=through_defaults,
  File "/home/suman/Desktop/suman1234/myvenv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 1129, in _add_items
    ], ignore_conflicts=True)
TypeError: _bulk_create() got an unexpected keyword argument 'ignore_conflicts'
```

**Comment by scshivam** [comment]
I have added a pull request. It worked after that:

https://github.com/martinphellwig/django-query-signals/pull/2
